### PR TITLE
Fix counting logic to avoid double counting

### LINKED ISSUE #45: Fix hop tracking
Per discussion in #39, let's make some fixes to this tracking logic.

### PR DESCRIPTION
**Pull request by bigs**
Closes #45

### CODE REVIEW

**Comment by bigs** [comment]
sorry for the delay @Stebalien , chgd

File: relay.go [hunk 1]
```diff
@@ -93,14 +93,19 @@ func (r *Relay) addLiveHop(from, to peer.ID) {
...
 	if !ok {
-		trg = make(map[peer.ID]struct{})
+		trg = make(map[peer.ID]int)
 		r.liveHops[from] = trg
 	}
+	var count int
+	if count, ok = trg[to]; !ok {
+		count = 0
+	}
+	count++
```
Comment (Stebalien) [inline relay.go]: We can replace all of this with `trg[to]++`. That will:

1. Lookup `to` in `trg`. If it's not there, it'll return 0.
2. Increment.
3. Set `trg[to]`.

Comment (bigs) [reply relay.go]: ahhh i was actually looking into these zero values and having a hard time finding out what was up. happy to change!
